name: Code Security Workflow

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  sca-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: SCA Scanning
        env:
          LOG_LEVEL: debug
        run: |
          npm install -g renovate
          renovate --token=${{ secrets.RENOVATE_TOKEN }} --dry-run .

      - name: Capture and Upload Logs
        run: |
          echo "Uploading Renovate Logs..." 
          touch renovate.log

      - name: Upload Logs 
        uses: actions/upload-artifact@v4
        with:
          name: renovate-logs
          path: renovate.log
